name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.8"
      - uses: actions/checkout@v3
      - run: "go vet"
